# -------------------------------------------------------------------------------------------------------------------------------- 
# This config uses Oh My ZSH and PowerLevel10k
# Made on ZSH 5.9 and Debian 13
# Oh My ZSH: https://github.com/ohmyzsh/ohmyzsh
# Powerlevel10k: https://github.com/romkatv/powerlevel10k
# Creator: https://github.com/DavidBalishyan
# Github repo: https://github.com/DavidBalishyan/dotfiles

# -------------------------------------------------------------------------------------------------------------------------------- 

# I don't need instant prompt
# ---------------------------------------------------------------------------------------------------------------------------
#	  																	 Enable Powerlevel10k instant prompt. 
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  # source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi
# Code, that requires input, should go on top of this.
# Everything else may go below
# --------------------------------------------------------------------------------------------------------------------------------

# --------------------------------------------------------------------------------------------------------------------------------
# 																									General configs
# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
# ZSH_THEME="robbyrussell"
# --------------------------------------------------------------------------------------------------------------------------------

plugins=(
	git
	zsh-plugin-rust
	you-should-use
	zsh-autosuggestions
  zsh-syntax-highlighting
)

# Source the oh-my-zsh activation script
source $ZSH/oh-my-zsh.sh

# To see a full list of active aliases run `alias`
alias reload="exec zsh"
alias ls="eza --git --icons"
alias bfetch="betterfetch"
alias vim="nvim"
alias myip="curl https://ipecho.net/plain ; echo"
alias cat="bat -pn"
alias t="tmux"
alias top="btop"
alias shck="shellcheck"
alias cls="clear -x"
# --------------------------------------------------------------------------------------------------------------------------------
# enable vi mode
set -o vi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# --------------------------------------------------------------------------------------------------------------------------------
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="/home/david/.nimble/bin:$PATH"
export PATH="/home/david/.config/herd-lite/bin:$PATH"
export PHP_INI_SCAN_DIR="/home/david/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"

# --------------------------------------------------------------------------------------------------------------------------------

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
eval "$(zoxide init zsh)"
eval "$(fzf --zsh)"
eval "$(thefuck --alias)"
eval "$(thefuck --alias fk)"

# --------------------------------------------------------------------------------------------------------------------------------

# pnpm
export PNPM_HOME="/home/david/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

export NVM_DIR="$HOME/.nvm"
[ -s "/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh" ] && \. "/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/david/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/david/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/david/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/david/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


# Just to show a nice fetch app when logged into the terminal
betterfetch

