backend = "glx";
vsync = true;
unredir-if-possible = true;

# Shadows
shadow = true;
shadow-radius = 10;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.5;

# Transparency / Fading
fading = true;
fade-delta = 5;
fade-in-step = 0.03;
fade-out-step = 0.03;
frame-opacity = 1.0;

# Corners
corner-radius = 8.0;

# Blur
blur-method = "dual_kawase";
blur-size = 8;
blur-strength = 7;
blur-background = true;

# General performance
use-damage = true;

# Window rules 
rules = (
  {
    match = "!focused";
    opacity = 0.9;
    inactive-opacity-override = false;
  },
  {
    match = "class_g = 'Polybar' || class_g = 'i3bar' || window_type = 'dock'";
    corner-radius = 0;
  },
  {
    match = "window_type = 'dock' || window_type = 'desktop'";
    blur-background = false;
  },
  {
    match = "name = 'Notification' || class_g = 'Conky' || class_g ?= 'Notify-osd' || class_g = 'i3-frame'";
    shadow = false;
  },
  {
    match = "class_g = 'URxvt'";
    opacity = 0.85;
  },
  {
    match = "class_g = 'kitty'";
    opacity = 0.90;
  },
  {
    match = "class_g = 'wezterm'";
    opacity = 1.0;
  },
  {
    match = "class_g = 'Polybar'";
    shadow = false;
    fade = false;
    blur-background = false;
    opacity = 1.0;
    corner-radius = 0;
  }
);

