#!/usr/bin/env python3

# bspwmrc is a shell script, by filtering out non-bspwm related lines we can
# simply rerun the script at runtime to apply changes.
# no idea why this isn't part of the wm

from sys import argv
from os import environ
from subprocess import call

def main():
    bspwmrc = argv[1] if (len(argv) > 1) else environ['HOME'] + '/.config/bspwm/bspwmrc'

    with open(bspwmrc) as configFile:
        for line in configFile:
            if line.startswith('bspc'):
                line.rstrip('\n')
                line = line.replace("\\", "")
                call(line.split())

if __name__ == '__main__':
    main()
