#!/bin/bash

source "$(dirname "$0")/board.bash"

list_themes() {
    info "Available Plymouth themes:"
    sudo plymouth-set-default-theme --list
}

set_theme() {
    local theme="$1"
    [[ -z "$theme" ]] && die "No theme specified."
    run sudo plymouth-set-default-theme -R "$theme"
    ok "Theme set and initramfs rebuilt."
}

update_grub() {
    info "Updating GRUB..."
    run sudo update-grub
    ok "GRUB updated."
}

preview_theme() {
    info "Previewing theme..."
    run sudo plymouthd
    run sudo plymouth --show-splash
    sleep 5
    run sudo plymouth --quit
    ok "Preview done."
}

header "Plymuth Theme Manager"
choose choice "Choose an option" "List available themes" "Set a theme" "Preview current theme" "Update GRUB" "Exit"

case "$choice" in
    "List available themes") list_themes ;;
    "Set a theme")
        prompt theme "Enter theme name"
        set_theme "$theme"
        ;;
    "Preview current theme") preview_theme ;;
    "Update GRUB") update_grub ;;
    "Exit") exit 0 ;;
esac


