#!/bin/bash

source "$(dirname "$0")/board.bash"

args=""
invalid_args=0
for arg; do
    case "$arg" in
        (*.c) arg=${arg%.c}; invalid_args=1;;
    esac
    args="$args $arg"
done
if [ $invalid_args -eq 1 ]; then
    die "Did you mean 'make$args'?" 1
fi

if [[ -d "$1" ]]; then
    die "$1 is a directory" 1
else
    run make -B -s "$@"
fi
