#!/usr/bin/env bash

source "$(dirname "$0")/board.bash"

for cmd in bash zsh fish; do
    if command -v "$cmd" &>/dev/null; then
        paint -n --green "$cmd: "
        $cmd --version | head -1
    else
        warn "$cmd not found"
    fi
done
