#!/usr/bin/env bash

source "$(dirname "$0")/board.bash"

if [[ -z "$TERMINAL" ]]; then
	die 'The $TERMINAL variable is not set' 126
else
	"$TERMINAL" -e "$SHELL" -c "$*; echo -e; $(paint -n --magenta --bold 'Press any key to exit') && read -s -n 1"
fi
